name: Python application

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install flake8 pytest
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

    - name: Lint with flake8
      run: |
        flake8 --exclude=venv

    - name: Run tests with pytest (handle no tests)
      run: |
        pytest || exit_code=$?
        if [ "$exit_code" -eq 5 ]; then
          echo "No tests found (exit code 5), ignoring"
          exit 0
        else
          exit $exit_code
        fi



